### PR TITLE
Update to support Cabal-1.24.0+

### PR DESCRIPTION
**Pull request by themattchan**

### CODE REVIEW

**Comment by nikivazou** [comment]
Hey @themattchan , so this just works?

**Comment by themattchan** [comment]
@nikivazou yep (I've moved development of my fork to https://github.com/awakesecurity/liquidhaskell-cabal/)

**Comment by Wizek** [comment]
Could it be that merging this (or some of the other PRs) would fix #10 ?

**Comment by spinda** [comment]
Thanks! I merged these along with #12.

**Pull request closed without merging**
