### PR TITLE
Cabal 1.24.0 compatibility

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Hrm, not ready for merge, looks like there are more `1.24` incompatibilities than just this one.

**Comment by mitchellwrosen** [comment]
Ok, I think this is good to go :+1:

**Comment by mitchellwrosen** [comment]
Wait! Still broken. Moment...

**Comment by mitchellwrosen** [comment]
Oh, apparently `liquidhaskell` itself currently only builds against GHC < 8

**Comment by spinda** [comment]
Thanks! `liquidhaskell-cabal` should work with Cabal 1.24+ now.

**Pull request closed without merging**
